import { HorseDivisionContext } from "@/generated/prisma/enums";

export const LISTING_OPTION_DEFAULTS = {
  disciplines: [
    "Hunter",
    "Jumper",
    "Equitation",
    "Eventing",
    "Dressage",
    "Polo",
    "Foxhunter",
    "English Pleasure",
    "Saddle Seat",
    "Combined Driving",
    "Trail Riding",
    "Pleasure Riding",
    "Other English",
  ],
  idealRiders: [
    "Junior",
    "Childrens Rider",
    "Adult Amateur",
    "Amateur",
    "Young Rider",
    "Professional",
    "Trainer Ride",
    "First Horse Rider",
    "Intermediate Rider",
    "Experienced Rider",
    "Family Rider",
    "Trail Rider",
  ],
  horseTypes: [
    "Prospect",
    "Young Prospect",
    "Schoolmaster",
    "Packer",
    "First Horse",
    "Move Up Horse",
    "Teacher Type",
    "Amateur Friendly",
    "Junior Friendly",
    "Childrens Horse",
    "Adult Amateur Horse",
    "Medal Horse",
    "Derby Horse",
    "Pony Hunter",
    "Equitation Horse",
    "Jumper Horse",
    "Event Horse",
    "Dressage Horse",
    "Polo Pony",
    "Foxhunter",
    "Pleasure Horse",
    "Trail Riding Only",
    "Pleasure Riding Only",
    "Breed Show Horse",
    "Broodmare Prospect",
    "Retirement or Companion",
  ],
  pricingVisibility: [
    "Contact for Price",
    "Serious Inquiries Only",
    "Lease Terms on Request",
    "Partnership or Syndication Inquiry",
    "Mid Five Figures",
    "High Five Figures",
    "Low Six Figures",
    "Mid Six Figures",
    "Seven Figures Plus",
    "Price Available by Direct Message",
  ],
  saleTypes: [
    "For Sale",
    "For Lease",
    "Lease to Purchase",
    "Inquire for Terms",
    "Partnership Opportunity",
  ],
  sexes: ["Gelding", "Mare", "Stallion"],
  colors: ["Bay", "Chestnut", "Black", "Gray", "Palomino", "Buckskin", "Pinto", "Roan", "Brown", "Other"],
  importStatuses: ["Imported", "Domestic", "Import Pending"],
  breeds: [
    "KWPN",
    "Dutch Warmblood",
    "Oldenburg",
    "Hanoverian",
    "Thoroughbred",
    "Quarter Horse",
    "Irish Sport Horse",
    "Connemara Cross",
    "Paint",
    "Belgian Warmblood",
    "Lusitano",
    "Westphalian",
    "Irish Draught Cross",
    "Warmblood",
    "Warmblood Cross",
  ],
  divisionsByDiscipline: {
    Hunter: [
      "Short Stirrup Hunter",
      "Long Stirrup Hunter",
      "Childrens Hunter 2 ft",
      "Childrens Hunter 2 ft 6",
      "Childrens Hunter 3 ft",
      "Adult Amateur Hunter 2 ft 6",
      "Adult Amateur Hunter 3 ft",
      "Junior Hunter 3 ft",
      "Junior Hunter 3 ft 3",
      "Junior Hunter 3 ft 6",
      "Amateur Owner Hunter 3 ft 3",
      "Amateur Owner Hunter 3 ft 6",
      "Performance Hunter 3 ft 3",
      "Performance Hunter 3 ft 6",
      "High Performance Hunter",
      "Green Hunter 3 ft",
      "Green Hunter 3 ft 3",
      "Green Hunter 3 ft 6",
      "Hunter Derby 2 ft 6",
      "Hunter Derby National",
      "Hunter Derby International",
      "Pony Hunter Small",
      "Pony Hunter Medium",
      "Pony Hunter Large",
      "Green Pony Hunter",
      "Local Hunter",
      "Outreach Hunter",
    ],
    Jumper: [
      "Cross Rails Jumper",
      "0.70m Jumper",
      "0.80m Jumper",
      "0.90m Jumper",
      "1.00m Jumper",
      "1.10m Jumper",
      "1.15m Jumper",
      "1.20m Jumper",
      "1.25m Jumper",
      "1.30m Jumper",
      "1.35m Jumper",
      "1.40m Jumper",
      "1.45m Jumper",
      "1.50m Plus Jumper",
      "FEI Jumper",
      "Childrens Jumper",
      "Adult Amateur Jumper",
      "Junior Jumper",
      "Schooling Jumper",
      "Young Jumper",
      "Grand Prix Prospect",
    ],
    Equitation: [
      "Short Stirrup Equitation",
      "Childrens Equitation 2 ft",
      "Childrens Equitation 2 ft 6",
      "Adult Equitation",
      "Pony Equitation",
      "2 ft 6 Equitation",
      "2 ft 9 Equitation",
      "3 ft Equitation",
      "3 ft 3 Equitation",
      "3 ft 6 Equitation",
      "3 ft 9 Plus Equitation",
      "Medal Horse",
      "USEF Medal Type",
      "NHS Type",
      "Maclay Type",
      "ASPCA Maclay Type",
      "Big Eq Horse",
    ],
    Eventing: [
      "Starter",
      "Beginner Novice",
      "Novice",
      "Training",
      "Modified",
      "Preliminary",
      "Intermediate",
      "Advanced",
      "FEI Eventing",
      "First Event Horse",
      "Junior Event Horse",
      "Amateur Event Horse",
      "Young Rider Horse",
      "Schoolmaster",
      "Move Up Event Horse",
    ],
    Dressage: [
      "Introductory",
      "Training Level",
      "First Level",
      "Second Level",
      "Third Level",
      "Fourth Level",
      "Prix St Georges",
      "Intermediate I",
      "Intermediate II",
      "Grand Prix",
      "FEI Young Horse",
      "Developing Horse",
      "Schoolmaster",
      "Upper Level Schoolmaster",
      "Amateur Friendly Dressage Horse",
      "Junior or Young Rider Dressage Horse",
    ],
    Polo: [
      "Beginner Polo",
      "Low Goal Polo",
      "Medium Goal Polo",
      "High Goal Polo",
      "Arena Polo",
      "Outdoor Polo",
      "Club Polo",
      "Tournament Polo",
      "Teaching Polo Pony",
      "String Horse",
    ],
    Foxhunter: [
      "First Flight",
      "Second Flight",
      "Field Hunter",
      "Staff Horse",
      "Amateur Foxhunter",
      "Foxhunter Prospect",
    ],
    "English Pleasure": [
      "Walk Trot",
      "Pleasure Schooling",
      "Local English Pleasure",
      "Show English Pleasure",
      "Amateur English Pleasure",
      "Junior English Pleasure",
    ],
    "Saddle Seat": [
      "Walk Trot Saddle Seat",
      "Three Gaited",
      "Five Gaited",
      "Pleasure Saddle Seat",
      "Amateur Saddle Seat",
      "Junior Saddle Seat",
    ],
    "Combined Driving": [
      "Training Level Driving",
      "Preliminary Driving",
      "Intermediate Driving",
      "Advanced Driving",
      "Pleasure Driving",
      "Carriage Driving",
    ],
    "Trail Riding": [
      "Trail Riding Only",
      "Pleasure Trail Horse",
      "Safe Trail Horse",
      "Family Trail Horse",
      "Beginner Trail Horse",
      "Experienced Trail Horse",
    ],
    "Pleasure Riding": [
      "Pleasure Riding Only",
      "Family Horse",
      "All Around Pleasure Horse",
      "Amateur Pleasure Horse",
      "Local Pleasure Horse",
    ],
    "Other English": [
      "Breed Show Horse",
      "In Hand Prospect",
      "Side Saddle",
      "Hunt Seat Pleasure",
      "Custom Other English Discipline",
    ],
  },
} as const;

export type ListingOptionCategory =
  | "disciplines"
  | "idealRiders"
  | "horseTypes"
  | "pricingVisibility"
  | "saleTypes"
  | "breeds"
  | "sires"
  | "dams"
  | "damSires"
  | "sexes"
  | "colors"
  | "importStatuses";

export const LISTING_OPTION_LABELS: Record<ListingOptionCategory, string> = {
  disciplines: "Primary Disciplines",
  idealRiders: "Ideal Rider",
  horseTypes: "Horse Type / Intended Use",
  pricingVisibility: "Pricing Visibility",
  saleTypes: "Sale Type",
  breeds: "Breed",
  sires: "Sire",
  dams: "Dam",
  damSires: "Dam Sire",
  sexes: "Sex",
  colors: "Color",
  importStatuses: "Import Status",
};

export function parseStringList(value: FormDataEntryValue | FormDataEntryValue[] | null | undefined) {
  const list = Array.isArray(value) ? value : value ? [value] : [];
  return list
    .map((entry) => String(entry).trim())
    .filter(Boolean);
}

export const HORSE_DIVISION_CONTEXTS: Array<{
  key: HorseDivisionContext;
  formKey: string;
  label: string;
  required: boolean;
}> = [
  {
    key: HorseDivisionContext.BEST_SUITED_FOR,
    formKey: "bestSuitedForIds",
    label: "Best Suited For",
    required: true,
  },
  {
    key: HorseDivisionContext.CURRENTLY_COMPETING_IN,
    formKey: "currentlyCompetingInIds",
    label: "Currently Competing In",
    required: false,
  },
  {
    key: HorseDivisionContext.EXPERIENCED_THROUGH,
    formKey: "experiencedThroughIds",
    label: "Experienced Through",
    required: false,
  },
];
